### ISSUE TITLE
having trouble getting it to work

### ISSUE THREAD

**Issue by leiringer** [Nordth/dojo-webpack-loader-examples#1]
First of all let me say thank you for writing this loader, however I'm having some trouble getting it to work. Would be great with a short example of how to use the loader.

**Comment by Nordth** [comment]
Thank you for your interest! I have uploaded some examples, hope they will help. Now I am also working on full documentation of loader i will add it in main repo after few days: https://github.com/Nordth/dojo-webpack-loader

**Comment by danice** [comment]
I have executed a `npm install`. 
Then the command `node_modules/.bin/webpack` returns some errors like 

> ERROR in ./src/dojo_01_animation.js
> Module not found: Error: Cannot resolve 'file' or 'directory' C:\Projects\dojo-webpack-loader-examples\dojo\dojo/_base/fx in C:\Projects\dojo-webpack-loader-examples\src
>  @ ./src/dojo_01_animation.js 2:13-37

and my folders 'C:\Projects\dojo-webpack-loader-examples\dojo' are empty. 
How should I load dojo to those folders? 

I'm very new to webpack and maybe there are obvious steps that I don't know, but please, could you give a short list of commands to get the examples working?

And of course, thanks a lot for your work! 

(by the way your project could solve [this webpack issue](https://github.com/webpack/webpack/issues/890)).

**Comment by leiringer** [comment]
When cloning the repo make sure you include submodules. [stackoverflow](http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules)

**Comment by danice** [comment]
Yes, was the submodules, it works now!

Used to work with jspm its amazing to me that no server its needed, just opening the html file!
